In [4]:
import yfinance as yf
import pandas as pd

In [6]:
tcs = yf.Ticker("TCS.NS")
# tcs_df = pd.DataFrame(tcs.info)
# tcs_df
tcs.info

{'address1': 'TCS House',
 'address2': 'Raveline Street Fort',
 'city': 'Mumbai',
 'zip': '400001',
 'country': 'India',
 'phone': '91 22 6778 9595',
 'website': 'https://www.tcs.com',
 'industry': 'Information Technology Services',
 'industryKey': 'information-technology-services',
 'industryDisp': 'Information Technology Services',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Tata Consultancy Services Limited provides information technology (IT) and IT enabled services worldwide. It operates through Banking, Financial Services and Insurance; Manufacturing; Retail and Consumer Business; Communication, Media and Technology; Life Sciences and Healthcare; and Others segments. The company provides TCS ADD, a suite of technology platforms for clinical research and drug development; TCS BaNCS, a financial solution platform; TCS BFSI Platforms, a cloud-native, as-a-service that helps FIs and insurance firms; TCS CHROMA, a cloud-based talent management solution; customer intelligence and insight solutions; TCS ERP on Cloud, a hosted ERP applications and services platform; TCS HOBS, a connected devices management platform; and ignio, an autonomous enterprise software. It also offers TCS Intelligent Urban Exchange, smart cities and enterprises solution; TCS OmniStore, a commerce platform; TCS OPTUMERA, a retail-connected strategic intelligence platform; TCS TAP, a procurement offering; TCS MasterCraft, a platform of intelligent automation products; Quartz- the Smart Ledgers, a blockchain solution; Jile, an enterprise agile planning and delivery tool; TCS iON, an IT-as-a-Service model that provides business solutions; and TCS TwinX, an enterprise digital twin platform. In addition, the company provides cloud, cognitive business, consulting, cybersecurity, data and analytics, enterprise solutions, Internet of Things and digital engineering, TCS interactive, and sustainability services. It serves capital markets; communications, media, and information services; public services; energy, resource, and utility industries; consumer goods and distribution industries; and banking, education, healthcare, high tech, insurance, life science, manufacturing, retail, travel, and logistics industries. The company was founded in 1968 and is headquartered in Mumbai, India. Tata Consultancy Services Limited is a subsidiary of Tata Sons Private Limited.',
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Ganapathy Subramaniam Natarajan M.Sc.',
   'age': 64,
   'title': 'COO & Non-Independent Executive Director',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 236020000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. K.  Krithivasan B.E, M.Tech.',
   'age': 59,
   'title': 'MD, CEO & Director',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Samir  Seksaria',
   'title': 'Chief Financial Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Sukanya  Sadasivan B.E',
   'age': 55,
   'title': 'Senior VP & Chief Information Officer',
   'yearBorn': 1968,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kedar  Shirali',
   'title': 'Head of Global Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Madhav  Anchan',
   'title': 'General Counsel Legal',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Pradeep Manohar Gaitonde',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Vivek  Padiyar',
   'title': 'Head of Corporate Communications',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Milind  Lakkad M.Tech.',
   'age': 59,
   'title': 'Chief Human Resources Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anita P. Nanadikar B.E',
   'age': 62,
   'title': 'Head of IOT & Incubation Group and VP',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 1,
 'boardRisk': 10,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 5,
 'overallRisk': 6,
 'governanceEpochDate': 1711929600,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 3872.8,
 'open': 3876.8,
 'dayLow': 3875.15,
 'dayHigh': 3916.0,
 'regularMarketPreviousClose': 3872.8,
 'regularMarketOpen': 3876.8,
 'regularMarketDayLow': 3875.15,
 'regularMarketDayHigh': 3916.0,
 'dividendRate': 51.0,
 'dividendYield': 0.013200001,
 'exDividendDate': 1705622400,
 'payoutRatio': 0.4051,
 'fiveYearAvgDividendYield': 1.28,
 'beta': 0.52,
 'trailingPE': 31.085245,
 'forwardPE': 24.85043,
 'volume': 1027151,
 'regularMarketVolume': 1027151,
 'averageVolume': 2586087,
 'averageVolume10days': 2988067,
 'averageDailyVolume10Day': 2988067,
 'bid': 3909.0,
 'ask': 3912.8,
 'marketCap': 14156500566016,
 'fiftyTwoWeekLow': 3078.0,
 'fiftyTwoWeekHigh': 4254.75,
 'priceToSalesTrailing12Months': 5.8766756,
 'fiftyDayAverage': 4033.948,
 'twoHundredDayAverage': 3679.8933,
 'trailingAnnualDividendRate': 55.0,
 'trailingAnnualDividendYield': 0.014201611,
 'currency': 'INR',
 'enterpriseValue': 13660376268800,
 'profitMargins': 0.19057,
 'floatShares': 1004477600,
 'sharesOutstanding': 3618089984,
 'heldPercentInsiders': 0.72431,
 'heldPercentInstitutions': 0.15555,
 'impliedSharesOutstanding': 3681989888,
 'bookValue': 249.97,
 'priceToBook': 15.6526785,
 'lastFiscalYearEnd': 1711843200,
 'nextFiscalYearEnd': 1743379200,
 'mostRecentQuarter': 1711843200,
 'earningsQuarterlyGrowth': 0.091,
 'netIncomeToCommon': 459080007680,
 'trailingEps': 125.87,
 'forwardEps': 157.45,
 'pegRatio': 3.35,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1527724800,
 'enterpriseToRevenue': 5.671,
 'enterpriseToEbitda': 21.246,
 '52WeekChange': 0.24735892,
 'SandP52WeekChange': 0.2160933,
 'lastDividendValue': 18.0,
 'lastDividendDate': 1705622400,
 'exchange': 'NSI',
 'quoteType': 'EQUITY',
 'symbol': 'TCS.NS',
 'underlyingSymbol': 'TCS.NS',
 'shortName': 'TATA CONSULTANCY S',
 'longName': 'Tata Consultancy Services Limited',
 'firstTradeDateEpochUtc': 1029123900,
 'timeZoneFullName': 'Asia/Kolkata',
 'timeZoneShortName': 'IST',
 'uuid': 'cc4c841e-ad42-3fdb-8d9f-b26fa8acd1cf',
 'messageBoardId': 'finmb_6411769',
 'gmtOffSetMilliseconds': 19800000,
 'currentPrice': 3912.7,
 'targetHighPrice': 4787.0,
 'targetLowPrice': 3040.0,
 'targetMeanPrice': 4184.98,
 'targetMedianPrice': 4300.0,
 'recommendationMean': 2.6,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 42,
 'totalCash': 447669993472,
 'totalCashPerShare': 123.666,
 'ebitda': 642959998976,
 'totalDebt': 80210001920,
 'quickRatio': 2.136,
 'currentRatio': 2.451,
 'totalRevenue': 2408930082816,
 'debtToEquity': 8.783,
 'revenuePerShare': 660.53,
 'returnOnAssets': 0.25556,
 'returnOnEquity': 0.50513,
 'freeCashflow': 379841249280,
 'operatingCashflow': 443380006912,
 'earningsGrowth': 0.104,
 'revenueGrowth': 0.035,
 'grossMargins': 0.40292,
 'ebitdaMargins': 0.26691,
 'operatingMargins': 0.25994,
 'financialCurrency': 'INR',
 'trailingPegRatio': 2.7591}

In [8]:
# get historical prices data (return is a DataFrame)
hist = tcs.history(period="max")
hist.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-08-12 00:00:00+05:30,27.430649,28.333789,27.430649,28.121286,212976,0.0,0.0
2002-08-13 00:00:00+05:30,28.156712,28.608283,27.536911,27.740559,153576,0.0,0.0
2002-08-14 00:00:00+05:30,27.802532,27.802532,25.305616,25.828022,822776,0.0,0.0
2002-08-15 00:00:00+05:30,25.828022,25.828022,25.828022,25.828022,0,0.0,0.0
2002-08-16 00:00:00+05:30,25.695204,26.917097,25.323322,25.766037,811856,0.0,0.0